FROM mcr.microsoft.com/devcontainers/base:1.2.6-ubuntu24.04

# Install the required dependencies
RUN apt-get update && apt-get install -y \
    pre-commit \
    python3-scipy \ 
    python3-ipykernel \ 
    python3-matplotlib \ 
    python3-msgpack \ 
    python3-pip \ 
    verilator \ 
    cmake

